name: Deploy Infrastructure

on:
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'terraform/**'
  workflow_dispatch: {
  }

jobs:
  deploy-beta:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      ENV_PREFIX: dev, 'prod'][github.ref_name == 'main' && 'prod' || github.ref_name == 'dev' && 'dev' || 'beta']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'
            cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -sout=tfplan
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan
      - name: Verify Deployment
        run: |
          echo "Verifying S3 Bucket Versioning..."
          aws s3api get-bucket-versioning --bucket ${{ env.S3_BUCKET }} --region ${{ env.AWS_REGION }}
            echo "Versioning should be Enabled."
          echo "Deployment to ${{ env.ENV_PREFIX }} environment completed."